### ISSUE TITLE
Should Quadrature take an `exact_to` optional argument?

### ISSUE THREAD

**Issue by thomasgibson** [inducer/modepy#33]
Let's say we want to create a quadrature rule outside the existing classes. For example, quadrature rules corresponding to "mass-matrix quadrature" used for subclasses of `_MassMatrixQuadratureElementGroup` in `meshmode`. It's simple enough to generate the weights and corresponding nodes. However, if we want to reason about the accuracy of the resulting quadrature rule, we're hosed (bam --- `quad.exact_to` raises an `AttributeError`).

I have already alluded to this problem [here](https://github.com/inducer/grudge/pull/62#discussion_r613554929). I proposed that `mp.Quadrature` be made an abstract class to _force a contract with the code_ --- quadrature rules should have specified accuracy. However, there are exceptions to this (notably `FejerQuadrature`)

How about we allow something like: `mp.Quadrature(nodes, weights, exact_to=order)`? Is this reasonable? If so, what should the default be for cases like `FejerQuadrature`? `None`?

Or should this be absorbed into https://github.com/inducer/modepy/issues/31 somehow?

**Comment by inducer** [comment]
I think the optional argument to `mp.Quadrature` is fine. Since the agreed-upon protocol for "I don't know" seems to be "raise `AttributeError`" (maybe document this while we're at it? We can do something that makes more sense with #31.), we can simply not set the attribute if it's not given. That way, we avoid imcompatibility with subclasses which have `exact_to` as a computed `@property`.

**Comment by inducer** [comment]
(cc @alexfikl, since you were part of the original discussion in https://github.com/inducer/grudge/pull/62)

**Comment by inducer** [comment]
(Opinions?)

**Comment by thomasgibson** [comment]
I just pushed a branch implementing the quick "band-aid" solution: https://github.com/inducer/modepy/commit/cbb4ccb8956cdd0c41c69770238e4bb752ba38ae

While I think this works, do you not think it's worth patching this up a bit more nicely (since we want to revise this as a whole anyways)?

A potentially nicer way may be to have a method for `Quadrature` and do something like:
```python
@property
def exact_to(self):
    try:
        return self._exact_to    # have to rename to something different
    except AttributeError:
        raise NotImplementedError(...)
```
This is certainly not the only option. A cleaner solution would be to go through the `@abstractproperty` route and implement methods that do the right thing (return `exact_to` for known cases, and return, say, an `Exception` for others).

**Comment by inducer** [comment]
Doing that breaks a healthy bunch of existing code:
```
$ git grep 'self.exact_to = '
contrib/weights-from-festa-sommariva.py:38:        self.exact_to = rule["quad_degree"]
modepy/quadrature/__init__.py:133:            self.exact_to = exact_to
modepy/quadrature/clenshaw_curtis.py:128:        self.exact_to = N
modepy/quadrature/grundmann_moeller.py:100:        self.exact_to = d
modepy/quadrature/jacobi_gauss.py:77:        self.exact_to = 2*N + 1
modepy/quadrature/vioreanu_rokhlin.py:107:        self.exact_to = order_table["quad_degree"]
modepy/quadrature/witherden_vincent.py:63:        self.exact_to = rule["quad_degree"]
modepy/quadrature/xiao_gimbutas.py:84:        self.exact_to = order
```
(Plus code outside of modepy that may do analogous things.)

**Comment by inducer** [comment]
In [this line](https://github.com/inducer/modepy/commit/cbb4ccb8956cdd0c41c69770238e4bb752ba38ae#diff-8f33cb19907be7b57be1f7e075fe4fd16c0a83c7bbdf07894e98bb3131c2a517R93), you comment
```
FIXME: This is not a sustainable solution.
```
What particular risk do you see? (honest question!)

**Comment by thomasgibson** [comment]
It just feels icky :sweat_smile: I can rephrase the comment. I guess I don't really like getting `AttributeError`s for "I don't know" (w.r.t. asking about quadrature accuracy).

I thought about adding a custom `RuntimeError`, something like `UnknownQuadratureOrderError`. But you already mentioned that it would break a lot of existing code.

**Comment by inducer** [comment]
> It just feels icky :sweat_smile:

I respect that. I agree that `AttributeError` is not a good protocol for "I don't know." (What makes me OK with it is that I do not see a correctness risk.)

I'm also OK with just setting `exact_to` to `None`. I don't think there's a correctness risk, it'll just crash user code that asks about exactness in a different way. I don't think we have code that defines `exact_to` as a property (otherwise that code would be broken by `self.exact_to =...`).

**Comment by alexfikl** [comment]
Not much to add here, besides agreeing that adding an `exact_to` argument to `Quadrature` is a good idea.

I would also prefer using `None` instead of raising an `AttributeError` when it's not known. Both choices would nicely crash code that tries to use `exact_to` as a number, so it's easy to catch.
